"""Add cascade delete to BookCategory

Revision ID: aa0a0e8e5f74
Revises: fc73138130dd
Create Date: 2024-08-21 18:17:09.560909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0a0e8e5f74'
down_revision = 'fc73138130dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    op.drop_constraint(None, 'book_categories', type_='foreignkey')
    op.create_foreign_key(None, 'book_categories', 'books', ['book_id'], ['book_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_categories', type_='foreignkey')
    op.create_foreign_key(None, 'book_categories', 'books', ['book_id'], ['book_id'])
    op.create_table('_alembic_tmp_users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
